### 11. Multimodal Data Integration

This notebook integrates the demographic, questionnaire, and wearable participant-level datasets to create the multimodal datasets required for the subsequent modeling experiments.

#### 1. Libraries and Project Paths

In [78]:
# =============================================================================
# Libraries and project paths
# =============================================================================

from pathlib import Path
import sys

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# =============================================================================
# Locate project root
# =============================================================================

cwd = Path.cwd()

if (cwd / "data").exists() and (cwd / "src").exists():
    PROJECT_ROOT = cwd

elif (cwd.parent / "data").exists() and (cwd.parent / "src").exists():
    PROJECT_ROOT = cwd.parent

else:
    raise FileNotFoundError(
        "Could not locate the project root containing data/ and src/."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ===========================================================
# Import shared modeling utilities
# ===========================================================
from src.modeling import outputs

# =============================================================================
# Import shared feature definitions
# =============================================================================

from src.modeling.feature_sets import (
    DEMOGRAPHIC_FEATURES,
    QUESTIONNAIRE_FEATURES,
    METADATA_COLUMNS,
    get_wearable_features,
)

# =============================================================================
# Define data paths
# =============================================================================

PROCESSED_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
)

DEMOGRAPHICS_FILE = (
    PROCESSED_DIR
    / "demographics_clean.csv"
)

QUESTIONNAIRE_FILE = (
    PROCESSED_DIR
    / "questionnaire_cleaned.csv"
)

WEARABLE_FILE = (
    PROCESSED_DIR
    / "wearable_features.csv"
)

print("Project root:", PROJECT_ROOT)
print("Processed data directory:", PROCESSED_DIR)
print("Demographics file:", DEMOGRAPHICS_FILE)
print("Questionnaire file:", QUESTIONNAIRE_FILE)
print("Wearable file:", WEARABLE_FILE)

Project root: c:\Users\Main\Documents\GitHub\AI-Assisted-Screening-of-Parkinson-s-Disease
Processed data directory: c:\Users\Main\Documents\GitHub\AI-Assisted-Screening-of-Parkinson-s-Disease\data\processed
Demographics file: c:\Users\Main\Documents\GitHub\AI-Assisted-Screening-of-Parkinson-s-Disease\data\processed\demographics_clean.csv
Questionnaire file: c:\Users\Main\Documents\GitHub\AI-Assisted-Screening-of-Parkinson-s-Disease\data\processed\questionnaire_cleaned.csv
Wearable file: c:\Users\Main\Documents\GitHub\AI-Assisted-Screening-of-Parkinson-s-Disease\data\processed\wearable_features.csv

#### 2. Load Source Datasets

The cleaned demographic, questionnaire, and participant-level wearable feature datasets were loaded as the input sources for multimodal integration. 

Participant identifiers were loaded as strings to preserve their original formatting and ensure consistent matching across datasets.

In [27]:
# =============================================================================
# Verify source files
# =============================================================================

source_files = {
    "Demographics": DEMOGRAPHICS_FILE,
    "Questionnaire": QUESTIONNAIRE_FILE,
    "Wearable": WEARABLE_FILE,
}

for dataset_name, file_path in source_files.items():

    if not file_path.exists():
        raise FileNotFoundError(
            f"{dataset_name} dataset not found: {file_path}"
        )

print("All source dataset found")

All source dataset found

In [28]:
# =============================================================================
# Load source datasets
# =============================================================================

demographics_df = pd.read_csv(
    DEMOGRAPHICS_FILE,
    dtype={"patient_id": str},
)

questionnaire_df = pd.read_csv(
    QUESTIONNAIRE_FILE,
    dtype={"patient_id": str},
)

wearable_df = pd.read_csv(
    WEARABLE_FILE,
    dtype={"patient_id": str},
)

print(
    "Demographics shape:",
    demographics_df.shape
)

print(
    "Questionnaire shape:",
    questionnaire_df.shape
)

print(
    "Wearable shape:",
    wearable_df.shape
)

Demographics shape: (469, 15)
Questionnaire shape: (469, 46)
Wearable shape: (469, 183)

#### 3. Define and Validate Modality Features

The modality-specific predictor sets were obtained from the shared feature definitions to preserve consistency with the Week 4 unimodal baseline experiments.

In [29]:
# =============================================================================
# Feature set
# =============================================================================

WEARABLE_FEATURES = get_wearable_features(
    wearable_df
)

print(
    "Demographic predictors:",
    len(DEMOGRAPHIC_FEATURES)
)

print(
    "Questionnaire predictors:",
    len(QUESTIONNAIRE_FEATURES)
)

print(
    "Wearable predictors:",
    len(WEARABLE_FEATURES)
)

Demographic predictors: 9
Questionnaire predictors: 41
Wearable predictors: 182

In [36]:
# =============================================================================
# Verify feature availability in source datasets
# =============================================================================

missing_demographic_features = [
    feature
    for feature in DEMOGRAPHIC_FEATURES
    if feature not in demographics_df.columns
]

missing_questionnaire_features = [
    feature
    for feature in QUESTIONNAIRE_FEATURES
    if feature not in questionnaire_df.columns
]

missing_wearable_features = [
    feature
    for feature in WEARABLE_FEATURES
    if feature not in wearable_df.columns
]

print(
    "Missing demographic features:",
    len(missing_demographic_features)
)

print(
    "Missing questionnaire features:",
    len(missing_questionnaire_features)
)

print(
    "Missing wearable features:",
    len(missing_wearable_features)
)

Missing demographic features: 0
Missing questionnaire features: 0
Missing wearable features: 0

In [37]:
assert not missing_demographic_features, (
    f"Missing demographic features: "
    f"{missing_demographic_features}"
)

assert not missing_questionnaire_features, (
    f"Missing questionnaire features: "
    f"{missing_questionnaire_features}"
)

assert not missing_wearable_features, (
    f"Missing wearable features: "
    f"{missing_wearable_features}"
)

print("All expected modality features found")

All expected modality features found

#### Observartion:
The demographic modality contains 9 predictors, the questionnaire modality contains 41 predictors, and the wearable modality contains 182 participant-level features.

#### 4. Verify Participant IDs and Duplicates

Before integrating the three data modalities, participant identifiers were validated to ensure that the demographic, questionnaire, and wearable datasets contained the same participant population.

In [38]:
# =============================================================================
# Verify patient_id column
# =============================================================================

source_datasets = {
    "Demographics": demographics_df,
    "Questionnaire": questionnaire_df,
    "Wearable": wearable_df,
}

for dataset_name, dataframe in source_datasets.items():

    if "patient_id" not in dataframe.columns:
        raise ValueError(
            f"{dataset_name} dataset does not contain patient_id."
        )

print("Patient_id column found in all source datasets")

Patient_id column found in all source datasets

In [39]:
# =============================================================================
# Verify participant counts and duplicates
# =============================================================================

participant_validation = []

for dataset_name, dataframe in source_datasets.items():

    total_rows = len(dataframe)

    unique_participants = (
        dataframe["patient_id"].nunique()
    )

    duplicated_participants = (
        dataframe["patient_id"]
        .duplicated()
        .sum()
    )

    participant_validation.append({
        "Dataset": dataset_name,
        "Rows": total_rows,
        "Unique Participants": unique_participants,
        "Duplicated Participants": duplicated_participants,
    })


participant_validation_df = pd.DataFrame(
    participant_validation
)

participant_validation_df

         Dataset  Rows  Unique Participants  Duplicated Participants
0   Demographics   469                  469                        0
1  Questionnaire   469                  469                        0
2       Wearable   469                  469                        0

In [40]:
# =============================================================================
# Validate expected participant structure
# =============================================================================

assert (
    participant_validation_df["Unique Participants"]
    == 469
).all(), (
    "One or more datasets do not contain 469 unique participants."
)

assert (
    participant_validation_df["Duplicated Participants"]
    == 0
).all(), (
    "Duplicated participant IDs were found."
)

print("Participant counts and duplicates verified")

Participant counts and duplicates verified

In [41]:
# =============================================================================
# Verify participant ID consistency across datasets
# =============================================================================

demographic_ids = set(
    demographics_df["patient_id"]
)

questionnaire_ids = set(
    questionnaire_df["patient_id"]
)

wearable_ids = set(
    wearable_df["patient_id"]
)

same_demographics_questionnaire = (
    demographic_ids
    == questionnaire_ids
)

same_demographics_wearable = (
    demographic_ids
    == wearable_ids
)

same_questionnaire_wearable = (
    questionnaire_ids
    == wearable_ids
)


participant_id_consistency = pd.DataFrame({
    "Dataset Comparison": [
        "Demographics vs Questionnaire",
        "Demographics vs Wearable",
        "Questionnaire vs Wearable",
    ],
    "Same Participant IDs": [
        same_demographics_questionnaire,
        same_demographics_wearable,
        same_questionnaire_wearable,
    ],
})

participant_id_consistency

              Dataset Comparison  Same Participant IDs
0  Demographics vs Questionnaire                  True
1       Demographics vs Wearable                  True
2      Questionnaire vs Wearable                  True

#### Observation: 
All three source datasets contained 469 unique participants with no duplicated participant identifiers. The participant ID sets were identical across the demographic, questionnaire, and wearable datasets, confirming that the three modalities can be safely integrated at the participant level using patient_id.

#### 5. Create Demographics + Questionnaire Dataset

In [42]:
# =============================================================================
# Select demographic and questionnaire columns
# =============================================================================

demographics_selected = demographics_df[
    [
        "patient_id",
        "condition_group",
        "label",
        *DEMOGRAPHIC_FEATURES,
    ]
].copy()

questionnaire_selected = questionnaire_df[
    [
        "patient_id",
        *QUESTIONNAIRE_FEATURES,
    ]
].copy()

print(
    "Demographics selected shape:",
    demographics_selected.shape
)

print(
    "Questionnaire selected shape:",
    questionnaire_selected.shape
)

Demographics selected shape: (469, 12)
Questionnaire selected shape: (469, 42)

In [43]:
# =============================================================================
# Merge demographics and questionnaire datasets
# =============================================================================

demographics_questionnaire_df = (
    demographics_selected
    .merge(
        questionnaire_selected,
        on="patient_id",
        how="inner",
        validate="one_to_one", # check that patient_id appears only once in each dataset
    )
)

print(
    "Demographics + Questionnaire shape:",
    demographics_questionnaire_df.shape
)

demographics_questionnaire_df.head()

Demographics + Questionnaire shape: (469, 53)

,patient_id,condition_group,label,age,age_at_diagnosis,height_cm,weight_kg,gender,handedness,family_history_any,family_history_first_degree,alcohol_effect_on_tremor,Q01,Q02,Q03,Q04,Q05,Q06,Q07,Q08,Q09,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,total_symptom_count,gastrointestinal_count,urinal_count,pain_count,miscellaneous_count,apathy_attention_memory_count,distortion_perception_count,depression_anxiety_count,sexual_function_count,cardiovascular_count,sleep_fatigue_count
0,1,Healthy Control,0,56.0,NaN,173.0,78.0,Male,Right,Yes,Yes,Unknown,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,Other Movement Disorder,2,81.0,69.0,193.0,104.0,Male,Right,No,Unknown,No Effect,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,1,0,1,0,12,2,1,0,1,0,1,1,0,3,3
2,3,Healthy Control,0,45.0,NaN,170.0,78.0,Female,Right,No,Unknown,Unknown,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,Parkinson's Disease,1,67.0,63.0,161.0,90.0,Female,Right,No,Unknown,No Effect,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,1,0,0,12,1,2,1,1,0,1,1,0,2,3
4,5,Parkinson's Disease,1,75.0,65.0,172.0,86.0,Male,Left,No,Unknown,Unknown,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,0,11,2,1,0,0,0,1,0,0,2,5

In [44]:
# =============================================================================
# Verify integrated dataset structure
# =============================================================================

expected_features = (
    len(DEMOGRAPHIC_FEATURES)
    + len(QUESTIONNAIRE_FEATURES)
)

expected_columns = (3 + expected_features)

print("Expected predictors:",
    expected_features
)

print("Actual predictors:",
    demographics_questionnaire_df.shape[1] - 3
)

print("Expected total columns:",
    expected_columns
)

print("Actual total columns:",
    demographics_questionnaire_df.shape[1]
)

Expected predictors: 50
Actual predictors: 50
Expected total columns: 53
Actual total columns: 53

In [46]:
assert len(demographics_questionnaire_df) == 469, (
    "Demographics + Questionnaire dataset "
    "does not contain 469 participants."
)

assert demographics_questionnaire_df[
    "patient_id"
].nunique() == 469, (
    "Unexpected duplicated or missing participant IDs."
)

assert (
    demographics_questionnaire_df.shape[1]
    == expected_columns
), (
    f"Expected {expected_columns} total columns, "
    f"found {demographics_questionnaire_df.shape[1]}."
)

print(
    "Demographics + Questionnaire dataset verified"
)

Demographics + Questionnaire dataset verified

In [47]:
# =============================================================================
# Verify no duplicated participants after integration
# =============================================================================

duplicated_participants = (
    demographics_questionnaire_df[
        "patient_id"
    ]
    .duplicated()
    .sum()
)

print(
    "Duplicated participants:",
    duplicated_participants
)

assert duplicated_participants == 0

print(
    "No duplicated patient_id found"
)

Duplicated participants: 0
No duplicated patient_id found

In [54]:
# =====================================================
# Brief integration summary
# =====================================================

demographics_questionnaire_summary = pd.DataFrame({
    "Metric": [
        "Patient_id",
        "Demographic features",
        "Questionnaire features",
        "Total predictors",
        "Total columns",
        "Duplicated participants",
    ],
    "Value": [
        len(demographics_questionnaire_df),
        len(DEMOGRAPHIC_FEATURES),
        len(QUESTIONNAIRE_FEATURES),
        expected_features,
        demographics_questionnaire_df.shape[1],
        duplicated_participants,
    ],
})

demographics_questionnaire_summary

                    Metric  Value
0               Patient_id    469
1     Demographic features      9
2   Questionnaire features     41
3         Total predictors     50
4            Total columns     53
5  Duplicated participants      0

#### Observation:
The Demographics + Questionnaire dataset was successfully created for all 469 participants. 

The integration retained 9 demographic predictors and 41 questionnaire predictors, resulting in 50 predictive features and 53 total columns including patient_id, condition_group, and label. 

No duplicated participants were introduced during the merge.

#### 6. Build Wearable + Questionnaire Dataset

In [49]:
# =============================================================================
# Select wearable, questionnaire, and target columns
# =============================================================================

wearable_selected = wearable_df[
    [
        "patient_id",
        *WEARABLE_FEATURES,
    ]
].copy()

questionnaire_selected = questionnaire_df[
    [
        "patient_id",
        *QUESTIONNAIRE_FEATURES,
    ]
].copy()

participant_labels = demographics_df[
    [
        "patient_id",
        "condition_group",
        "label",
    ]
].copy()

print(
    "Wearable selected shape:",
    wearable_selected.shape
)

print(
    "Questionnaire selected shape:",
    questionnaire_selected.shape
)

print(
    "Participant labels shape:",
    participant_labels.shape
)

Wearable selected shape: (469, 183)
Questionnaire selected shape: (469, 42)
Participant labels shape: (469, 3)

In [50]:
# =============================================================================
# Merge wearable and questionnaire datasets
# =============================================================================

wearable_questionnaire_df = (
    wearable_selected
    .merge(
        questionnaire_selected,
        on="patient_id",
        how="inner",
        validate="one_to_one",
    )
)

In [51]:
wearable_questionnaire_df = (
    participant_labels
    .merge(
        wearable_questionnaire_df,
        on="patient_id",
        how="inner",
        validate="one_to_one",
    )
)

print(
    "Wearable + Questionnaire shape:",
    wearable_questionnaire_df.shape
)

wearable_questionnaire_df.head()

Wearable + Questionnaire shape: (469, 226)

,patient_id,condition_group,label,time_Accelerometer_X_Mean,time_Accelerometer_X_Median,time_Accelerometer_X_Std,time_Accelerometer_X_Min,time_Accelerometer_X_Max,time_Accelerometer_X_Range,time_Accelerometer_X_IQR,time_Accelerometer_X_RMS,time_Accelerometer_X_Energy,time_Accelerometer_Y_Mean,time_Accelerometer_Y_Median,time_Accelerometer_Y_Std,time_Accelerometer_Y_Min,time_Accelerometer_Y_Max,time_Accelerometer_Y_Range,time_Accelerometer_Y_IQR,time_Accelerometer_Y_RMS,time_Accelerometer_Y_Energy,time_Accelerometer_Z_Mean,time_Accelerometer_Z_Median,time_Accelerometer_Z_Std,time_Accelerometer_Z_Min,time_Accelerometer_Z_Max,time_Accelerometer_Z_Range,time_Accelerometer_Z_IQR,time_Accelerometer_Z_RMS,time_Accelerometer_Z_Energy,time_Gyroscope_X_Mean,time_Gyroscope_X_Median,time_Gyroscope_X_Std,time_Gyroscope_X_Min,time_Gyroscope_X_Max,time_Gyroscope_X_Range,time_Gyroscope_X_IQR,time_Gyroscope_X_RMS,time_Gyroscope_X_Energy,time_Gyroscope_Y_Mean,time_Gyroscope_Y_Median,time_Gyroscope_Y_Std,time_Gyroscope_Y_Min,time_Gyroscope_Y_Max,time_Gyroscope_Y_Range,time_Gyroscope_Y_IQR,time_Gyroscope_Y_RMS,time_Gyroscope_Y_Energy,time_Gyroscope_Z_Mean,time_Gyroscope_Z_Median,time_Gyroscope_Z_Std,time_Gyroscope_Z_Min,time_Gyroscope_Z_Max,time_Gyroscope_Z_Range,time_Gyroscope_Z_IQR,time_Gyroscope_Z_RMS,time_Gyroscope_Z_Energy,time_Acc_Magnitude_Mean,time_Acc_Magnitude_Median,time_Acc_Magnitude_Std,time_Acc_Magnitude_Min,time_Acc_Magnitude_Max,time_Acc_Magnitude_Range,time_Acc_Magnitude_IQR,time_Acc_Magnitude_RMS,time_Acc_Magnitude_Energy,time_Gyro_Magnitude_Mean,time_Gyro_Magnitude_Median,time_Gyro_Magnitude_Std,time_Gyro_Magnitude_Min,time_Gyro_Magnitude_Max,time_Gyro_Magnitude_Range,time_Gyro_Magnitude_IQR,time_Gyro_Magnitude_RMS,time_Gyro_Magnitude_Energy,freq_n_samples,freq_original_sampling_frequency_hz,freq_sampling_frequency_hz,freq_resampled_n_samples,freq_uniform_time_start_s,freq_uniform_time_end_s,freq_acc_x_dominant_frequency,freq_acc_x_spectral_centroid,freq_acc_x_spectral_entropy,freq_acc_x_spectral_power,freq_acc_y_dominant_frequency,freq_acc_y_spectral_centroid,freq_acc_y_spectral_entropy,freq_acc_y_spectral_power,freq_acc_z_dominant_frequency,freq_acc_z_spectral_centroid,freq_acc_z_spectral_entropy,freq_acc_z_spectral_power,freq_acc_magnitude_dominant_frequency,freq_acc_magnitude_spectral_centroid,freq_acc_magnitude_spectral_entropy,freq_acc_magnitude_spectral_power,freq_gyro_x_dominant_frequency,freq_gyro_x_spectral_centroid,freq_gyro_x_spectral_entropy,freq_gyro_x_spectral_power,freq_gyro_y_dominant_frequency,freq_gyro_y_spectral_centroid,freq_gyro_y_spectral_entropy,freq_gyro_y_spectral_power,freq_gyro_z_dominant_frequency,freq_gyro_z_spectral_centroid,freq_gyro_z_spectral_entropy,freq_gyro_z_spectral_power,freq_gyro_magnitude_dominant_frequency,freq_gyro_magnitude_spectral_centroid,freq_gyro_magnitude_spectral_entropy,freq_gyro_magnitude_spectral_power,symmetry_Accelerometer_X_Mean_difference,symmetry_Accelerometer_X_Median_difference,symmetry_Accelerometer_X_Std_difference,symmetry_Accelerometer_X_Min_difference,symmetry_Accelerometer_X_Max_difference,symmetry_Accelerometer_X_Range_difference,symmetry_Accelerometer_X_IQR_difference,symmetry_Accelerometer_X_RMS_difference,symmetry_Accelerometer_X_Energy_difference,symmetry_Accelerometer_Y_Mean_difference,symmetry_Accelerometer_Y_Median_difference,symmetry_Accelerometer_Y_Std_difference,symmetry_Accelerometer_Y_Min_difference,symmetry_Accelerometer_Y_Max_difference,symmetry_Accelerometer_Y_Range_difference,symmetry_Accelerometer_Y_IQR_difference,symmetry_Accelerometer_Y_RMS_difference,symmetry_Accelerometer_Y_Energy_difference,symmetry_Accelerometer_Z_Mean_difference,symmetry_Accelerometer_Z_Median_difference,symmetry_Accelerometer_Z_Std_difference,symmetry_Accelerometer_Z_Min_difference,symmetry_Accelerometer_Z_Max_difference,symmetry_Accelerometer_Z_Range_difference,symmetry_Accelerometer_Z_IQR_difference,symmetry_Accelerometer_Z_RMS_difference,symmetry_Accelerometer_Z_Energy_difference,symmetry_Gyroscope_X_Mean_difference,symmetry_Gyroscope_X_Median_difference,symmetry_Gyroscope_X_Std_difference,symmetry_Gyroscope_X_Min_difference,symmetry_Gyroscope_X_Max_difference,symmetry_Gyroscope_X_Range_difference,symmetry_Gyroscope_X_IQR_difference,symmetry_Gyroscope_X_RMS_difference,symmetry_Gyroscope_X_Energy_difference,symmetry_Gyroscope_Y_Mean_difference,symmetry_Gyroscope_Y_Median_difference,symmetry_Gyroscope_Y_Std_difference,symmetry_Gyroscope_Y_Min_difference,symmetry_Gyroscope_Y_Max_difference,symmetry_Gyroscope_Y_Range_difference,symmetry_Gyroscope_Y_IQR_difference,symmetry_Gyroscope_Y_RMS_difference,symmetry_Gyroscope_Y_Energy_difference,symmetry_Gyroscope_Z_Mean_difference,symmetry_Gyroscope_Z_Median_difference,symmetry_Gyroscope_Z_Std_difference,symmetry_Gyroscope_Z_Min_difference,symmetry_Gyroscope_Z_Max_difference,symmetry_Gyroscope_Z_Range_difference,symmetry_Gyroscope_Z_IQR_difference,symmetry_Gyroscope_Z_RMS_difference,symmetry_Gyroscope_Z_Energy_difference,symmetry_Acc_Magnitude_Mean_difference,symmetry_Acc_Magnitude_Median_difference,symmetry_Acc_Magnitude_Std_difference,symmetry_Acc_Magnitude_Min_difference,symmetry_Acc_Magnitude_Max_difference,symmetry_Acc_Magnitude_Range_difference,symmetry_Acc_Magnitude_IQR_difference,symmetry_Acc_Magnitude_RMS_difference,symmetry_Acc_Magnitude_Energy_difference,symmetry_Gyro_Magnitude_Mean_difference,symmetry_Gyro_Magnitude_Median_difference,symmetry_Gyro_Magnitude_Std_difference,symmetry_Gyro_Magnitude_Min_difference,symmetry_Gyro_Magnitude_Max_difference,symmetry_Gyro_Magnitude_Range_difference,symmetry_Gyro_Magnitude_IQR_difference,symmetry_Gyro_Magnitude_RMS_difference,symmetry_Gyro_Magnitude_Energy_difference,Q01,Q02,Q03,Q04,Q05,Q06,Q07,Q08,Q09,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,total_symptom_count,gastrointestinal_count,urinal_count,pain_count,miscellaneous_count,apathy_attention_memory_count,distortion_perception_count,depression_anxiety_count,sexual_function_count,cardiovascular_count,sleep_fatigue_count
0,1,Healthy Control,0,-0.000155,0.004059,0.074081,-0.513615,0.233092,0.746707,0.059540,0.074046,14.549401,0.000101,-0.000815,0.087478,-0.376868,0.441544,0.818412,0.066308,0.087440,15.694766,-0.000111,0.001951,0.092351,-0.514622,0.287520,0.802142,0.077791,0.092315,19.727217,0.001958,-0.007048,0.733113,-3.022237,2.744726,5.766962,0.454378,0.734694,1451.533057,-0.059348,-0.041810,0.680479,-1.848660,1.860104,3.708764,0.620630,0.689235,1062.160499,0.015561,0.018341,0.946153,-2.392659,2.397176,4.789835,0.904805,0.950492,2117.577259,0.104609,0.076229,0.101005,0.007341,0.872564,0.865224,0.082269,0.148856,49.971383,1.044496,0.770702,0.979678,0.016680,4.515957,4.499278,1.270267,1.454627,4631.270815,1255.272727,99.695771,100.0,1255.272727,0.0,12.542727,3.058122,6.230525,0.694262,0.012787,2.332340,5.676603,0.687384,0.013938,2.097765,5.248369,0.645296,0.020098,1.035917,5.406945,0.635161,0.025970,1.884724,3.646866,0.583616,1.226957,1.054769,2.351818,0.496097,0.982722,1.077794,2.210475,0.466672,1.788369,0.558197,2.891241,0.510830,1.563943,0.000126,0.000751,0.002687,0.020347,0.081354,0.061007,-0.001020,0.002685,3.926234,-0.000961,0.007324,0.000740,-0.250956,-0.224631,0.026325,0.007206,0.000733,0.501690,0.000144,-0.002419,-0.010846,0.119935,0.008180,-0.111756,-0.006738,-0.010827,-2.796376,-0.059027,0.001298,-0.183969,0.502048,-1.044879,-1.546927,0.030725,-0.186072,-763.401893,0.054845,0.026634,-0.056368,0.315671,-0.155424,-0.471095,-0.065901,-0.063544,-195.361523,-0.059173,-0.051094,-0.054036,0.280625,-0.138113,-0.418738,-0.137933,-0.053825,15.208446,-0.003837,-0.000955,-0.003630,-0.000847,-0.139103,-0.138256,-0.000969,-0.004155,1.631548,-0.126805,-0.085487,-0.123576,-0.007836,-0.317006,-0.309170,-0.028445,-0.179823,-943.554969,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,Other Movement Disorder,2,0.000043,-0.000302,0.062226,-0.365569,0.382510,0.748079,0.057380,0.062207,6.704495,-0.000565,-0.002381,0.104161,-0.519660,0.738762,1.258423,0.095721,0.104117,18.189232,-0.000027,0.002218,0.093746,-0.893036,0.324629,1.217665,0.072578,0.093704,17.435516,0.004577,0.005402,0.650489,-2.453989,2.730280,5.184269,0.561365,0.651251,969.586073,-0.005982,0.001440,0.489375,-1.470359,1.417012,2.887371,0.583114,0.496117,548.688799,-0.007127,-0.009160,0.432280,-1.367154,1.353047,2.720201,0.318673,0.436265,436.299754,0.114448,0.086625,0.109235,0.005603,1.169167,1.163564,0.086983,0.160501,42.329243,0.757657,0.606165,0.633197,0.024009,3.628187,3.604178,0.719134,1.001763,1954.574626,1255.272727,99.693186,100.0,1255.272727,0.0,12.542727,3.138301,5.626025,0.665201,0.004732,4.510022,6.712393,0.643320,0.020066,3.251639,6.144094,0.672994,0.012731,1.248212,5.421935,0.645448,0.018075,3.360618,4.732639,0.599669,1.017963,2.336848,3.158048,0.498420,0.455997,1.992735,2.448173,0.482142,0.353557,0.896013,3.300614,0.536026,0.704772,0.000311,0.003689,-0.000609,0.157281,-0.055430,-0.212710,0.003881,-0.000597,-0.070427,0.000056,0.004194,-0.034243,0.327178,-0.234006,-0.561184,-0.032424,-0.034220,-11.511198,0.000241,-0.002189,0.000195,0.247575,0.033844,-0.213731,0.012567,0.000196,-0.051752,-0.016074,0.017275,-0.131226,0.373396,-0.926270,-1.299666,-0.282290,-0.130117,-110.430912,0.068725,-0.047424,0.103311,-0.290733,0.284144,0.574877,0.084738,0.104329,280.149633,-0.034046,0.005500,-0.012717,0.131622,-0.025563,-0.157185,-0.075927,-0.012010,32.709000,-0.017563,-0.013608,-0.022999,0.001122,-0.291124,-0.292246,-0.028135,-0.029868,-11.633377,-0.064486,-0.106319,0.023457,-0.004497,-0.520227,-0.515729,-0.031305,-0.028431,202.427722,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,1,0,1,0,12,2,1,0,1,0,1,1,0,3,3
2,3,Healthy Control,0,-0.000092,-0.000014,0.089180,-0.364048,0.331769,0.695817,0.094730,0.089143,20.022262,-0.000301,-0.007162,0.094037,-0.318494,0.432975,0.751469,0.115303,0.094001,23.441925,0.000737,0.015611,0.135424,-0.688083,0.281203,0.969286,0.154435,0.135364,49.596858,0.029004,-0.011867,0.677988,-2.138622,2.153938,4.292560,0.649373,0.680796,1394.784319,0.021482,-0.007202,0.724062,-1.707368,1.946701,3.654068,0.919674,0.730784,1450.953032,-0.000909,0.005118,1.066673,-2.106831,2.132905,4.239737,1.579971,1.070579,4119.246211,0.156118,0.131845,0.102425,0.017890,0.807261,0.789371,0.088695,0.189295,93.061045,1.280202,1.214987,0.841563,0.051751,3.553962,3.502210,1.220953,1.565628,6964.983562,1255.272727,99.709030,100.0,1255.272727,0.0,12.542727,2.486811,5.291730,0.627177,0.020999,2.509985,5.976405,0.669272,0.022802,2.531371,4.691297,0.585639,0.049827,1.592921,4.871101,0.605607,0.024221,2.768852,3.821132,0.526641,1.590024,1.928390,2.822770,0.511789,1.428762,1.426565,2.503264,0.432065,4.204214,1.033793,3.088925,0.472244,1.678728,0.000396,-0.001194,0.005026,0.115035,0.146842,0.031807,0.007943,0.005028,2.695090,-0.001060,0.001880,0.007266,-0.136103,0.025483,0.161586,0.000323,0.007272,1.984549,0.000258,-0.005150,-0.003860,-0.066855,-0.014438,0.052417,-0.004143,-0.003866,-3.692288,0.026944,0.012724,0.095199,-0.862230,0.598981,1.461210,-0.000433,0.094778,466.946269,0.119367,0.047168,0.094969,-0.070942,0.548340,0.619282,-0.073892,0.099582,290.213950,-0.082715,-0.101567,0.033037,-0.317696,-0.242002,0.075694,0.041209,0.032811,168.383594,0.002917,0.002024,-0.001463,0.003127,-0.076150,-0.079277,-0.009884,0.001244,0.987351,0.068282,0.084292,0.060849,0.017704,0.438968,0.421265,0.056464,0.092100,925.543812,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,Parkinson's Disease,1,-0.000061,-0.000984,0.035592,-0.177022,0.220743,0.397765,0.024906,0.035588,4.321860,0.000041,-0.003340,0.047037,-0.181449,0.383989,0.565438,0.042677,0.047019,6.817805,0.000122,0.002667,0.057104,-0.433757,0.146561,0.580318,0.044076,0.057081,12.719649,0.033283,0.010237,0.381022,-1.100282,1.359733,2.460015,0.339980,0.385037,436.801061,-0.022131,-0.015391,0.367558,-0.909074,0.870891,1.779965,0.343455,0.378334,414.539711,0.010895,0.000858,0.494688,-1.054148,1.056314,2.110463,0.541144,0.504157,864.154799,0.056969,0.041472,0.059839,0.003204,0.640202,0.636999,0.037442,0.083185,23.859315,0.573044,0.487765,0.469875,0.008791,2.029775,2.020984,0.536433,0.756978,1715.495571,1255.272727,99.688082,100.0,1255.272727,0.0,12.542727,1.947578,6.481895,0.723869,0.004170,2.554732,6.340352,0.714052,0.006094,1.834426,6.317018,0.715528,0.012909,0.319821,4.691237,0.569417,0.012140,0.734762,2.900242,0.536754,0.455841,0.447727,1.512428,0.408111,0.405129,1.101155,1.652757,0.376839,0.878390,0.406483,1.821555,0.388259,0.476171,-0.000216,-0.003590,0.010988,0.067240,0.161462,0.094221,0.008039,0.010974,2.495382,0.000139,0.002171,-0.002178,0.015928,-0.285778,-0.301706,0.003137,-0.002181,-1.695210,0.000120,-0.000610,-0.001723,0.025174,-0.009372,-0.034546,-0.000607,-0.001721,-3.304850,0.008130,0.000249,0.003187,0.038054,0.032954,-0.005100,0.035377,0.006207,-111.997554,0.109129,0.003112,0.024357,0.151364,0.312854,0.161490,0.069241,0.018712,59.644272,-0.093433,-0.082899,-0.019947,-0.015903,-0.142037,-0.126134,0.056947,-0.022713,-17.439135,0.006131,0.005927,-0.003271,-0.001016,-0.178047,-0.177031,0.005030,0.001918,-2.504678,0.014927,0.036575,0.000743,0.001043,0.170965,0.169922,0.052439,0.012388,-69.792417,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,1,0,0,12,1,2,1,1,0,1,1,0,2,3
4,5,Parkinson's Disease,1,-0.000042,-0.000507,0.060632,-0.213993,0.233428,0.447422,0.075401,0.060610,6.021132,-0.000057,-0.004129,0.112425,-0.378152,0.487117,0.865269,0.134627,0.112379,21.995114,0.000093,0.000291,0.085675,-0.423143,0.275818,0.698960,0.101231,0.085640,13.777724,0.011549,-0.027006,0.645503,-1.912828,2.104835,4.017662,0.806418,0.646599,832.304926,0.004951,-0.006397,0.480587,-1.209166,1.141830,2.350996,0.679565,0.482465,479.121452,-0.001718,0.014468,0.625390,-1.488436,1.340937,2.829373,0.801986,0.630553,837.506745,0.132930,0.115005,0.082380,0.010615,0.643581,0.632966,0.087794,0.157051,41.793970,0.911229,0.839022,0.579518,0.032670,2.942777,2.910107,0.781414,1.093297,2148.933124,1255.272727,99.704327,100.0,1255.272727,0.0,12.542727,3.651080,5.317646,0.625702,0.004385,4.798063,6.003697,0.627012,0.016508,4.452608,5.510266,0.634168,0.011136,1.317027,6.100467,0.693698,0.008332,3.281073,4.893018,0.559370,0.635074,3.784277,3.503301,0.485392,0.459802,2.552124,2.723202,0.428897,0.744560,0.902012,3.742713,0.531731,0.418009,0.000666,0.004864,-0.028622,0.059647,-0.083144,-0.142791,-0.040769,-0.028618,-4.931818,0.000078,0.000180,-0.087726,0.280731,-0.307485,-0.588217,-0.113701,-0.087688,-27.370468,-0.000308,-0.002016,-0.036532,0.053178,-0.075571,-0.128750,-0.055824,-0.036522,-7.213784,0.020806,0.002986,-0.484805,1.458950,-0.909971,-2.368921,-0.713642,-0.482536,-918.820951,0.019364,-0.021701,-0.044140,0.151927,-0.150082,-0.302009,-0.107205,-0.043082,121.869381,-0.045455,-0.069661,-0.108596,0.250952,-0.380163,-0.631115,-0.179864,-0.104153,-36.109681,-0.087400,-0.079773,-0.042269,-0.009043,-0.245858,-0.236815,-0.061590,-0.096167,-39.516070,-0.404767,-0.398273,-0.190974,-0.010912,-1.140813,-1.129902,-0.373412,-0.428032,-833.061251,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,0,11,2,1,0,0,0,1,0,0,2,5

In [52]:
# =============================================================================
# Verify integrated dataset structure
# =============================================================================

expected_wq_features = (
    len(WEARABLE_FEATURES)
    + len(QUESTIONNAIRE_FEATURES)
)

expected_wq_columns = (3 + expected_wq_features)

print("Expected predictors:",
    expected_wq_features
)

print("Actual predictors:",
    wearable_questionnaire_df.shape[1] - 3
)

print("Expected total columns:",
    expected_wq_columns
)

print("Actual total columns:",
    wearable_questionnaire_df.shape[1]
)

Expected predictors: 223
Actual predictors: 223
Expected total columns: 226
Actual total columns: 226

In [53]:
# =============================================================================
# Verify participant structure
# =============================================================================

assert len(wearable_questionnaire_df) == 469, (
    "Wearable + Questionnaire dataset "
    "does not contain 469 participants."
)

assert wearable_questionnaire_df[
    "patient_id"
].nunique() == 469, (
    "Unexpected missing or duplicated participant IDs."
)

duplicated_wq_participants = (
    wearable_questionnaire_df[
        "patient_id"
    ]
    .duplicated()
    .sum()
)

assert duplicated_wq_participants == 0, (
    "Duplicated participants were introduced during integration."
)

assert (
    wearable_questionnaire_df.shape[1]
    == expected_wq_columns
), (
    f"Expected {expected_wq_columns} total columns, "
    f"found {wearable_questionnaire_df.shape[1]}."
)

print(
    "Wearable + Questionnaire dataset verified"
)

Wearable + Questionnaire dataset verified

In [55]:
wearable_questionnaire_summary = pd.DataFrame({
    "Metric": [
        "Patient_id",
        "Wearable features",
        "Questionnaire features",
        "Total predictors",
        "Total columns",
        "Duplicated participants",
    ],
    "Value": [
        len(wearable_questionnaire_df),
        len(WEARABLE_FEATURES),
        len(QUESTIONNAIRE_FEATURES),
        expected_wq_features,
        wearable_questionnaire_df.shape[1],
        duplicated_wq_participants,
    ],
})

wearable_questionnaire_summary

                    Metric  Value
0               Patient_id    469
1        Wearable features    182
2   Questionnaire features     41
3         Total predictors    223
4            Total columns    226
5  Duplicated participants      0

#### Observation: 

The Wearable + Questionnaire dataset was successfully created for all 469 participants. The integration combined 182 wearable predictors and 41 questionnaire predictors, resulting in 223 predictive features

#### 7. Build Full Multimodal Dataset

The three participant-level modalities were integrated to create the full multimodal dataset used for subsequent modeling experiments.

In [56]:
# =============================================================================
# Select columns for full multimodal integration
# =============================================================================

demographics_full_selected = demographics_df[
    [
        "patient_id",
        "condition_group",
        "label",
        *DEMOGRAPHIC_FEATURES,
    ]
].copy()

questionnaire_full_selected = questionnaire_df[
    [
        "patient_id",
        *QUESTIONNAIRE_FEATURES,
    ]
].copy()

wearable_full_selected = wearable_df[
    [
        "patient_id",
        *WEARABLE_FEATURES,
    ]
].copy()

In [57]:
# =============================================================================
# Merge the three modalities
# =============================================================================

# Merge demographics and questionnaire
multimodal_full_df = (
    demographics_full_selected
    .merge(
        questionnaire_full_selected,
        on="patient_id",
        how="inner",
        validate="one_to_one",
    )
)

# Add wearable features
multimodal_full_df = (
    multimodal_full_df
    .merge(
        wearable_full_selected,
        on="patient_id",
        how="inner",
        validate="one_to_one",
    )
)

print(
    "Full multimodal dataset shape:",
    multimodal_full_df.shape
)

multimodal_full_df.head()

Full multimodal dataset shape: (469, 235)

,patient_id,condition_group,label,age,age_at_diagnosis,height_cm,weight_kg,gender,handedness,family_history_any,family_history_first_degree,alcohol_effect_on_tremor,Q01,Q02,Q03,Q04,Q05,Q06,Q07,Q08,Q09,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,total_symptom_count,gastrointestinal_count,urinal_count,pain_count,miscellaneous_count,apathy_attention_memory_count,distortion_perception_count,depression_anxiety_count,sexual_function_count,cardiovascular_count,sleep_fatigue_count,time_Accelerometer_X_Mean,time_Accelerometer_X_Median,time_Accelerometer_X_Std,time_Accelerometer_X_Min,time_Accelerometer_X_Max,time_Accelerometer_X_Range,time_Accelerometer_X_IQR,time_Accelerometer_X_RMS,time_Accelerometer_X_Energy,time_Accelerometer_Y_Mean,time_Accelerometer_Y_Median,time_Accelerometer_Y_Std,time_Accelerometer_Y_Min,time_Accelerometer_Y_Max,time_Accelerometer_Y_Range,time_Accelerometer_Y_IQR,time_Accelerometer_Y_RMS,time_Accelerometer_Y_Energy,time_Accelerometer_Z_Mean,time_Accelerometer_Z_Median,time_Accelerometer_Z_Std,time_Accelerometer_Z_Min,time_Accelerometer_Z_Max,time_Accelerometer_Z_Range,time_Accelerometer_Z_IQR,time_Accelerometer_Z_RMS,time_Accelerometer_Z_Energy,time_Gyroscope_X_Mean,time_Gyroscope_X_Median,time_Gyroscope_X_Std,time_Gyroscope_X_Min,time_Gyroscope_X_Max,time_Gyroscope_X_Range,time_Gyroscope_X_IQR,time_Gyroscope_X_RMS,time_Gyroscope_X_Energy,time_Gyroscope_Y_Mean,time_Gyroscope_Y_Median,time_Gyroscope_Y_Std,time_Gyroscope_Y_Min,time_Gyroscope_Y_Max,time_Gyroscope_Y_Range,time_Gyroscope_Y_IQR,time_Gyroscope_Y_RMS,time_Gyroscope_Y_Energy,time_Gyroscope_Z_Mean,time_Gyroscope_Z_Median,time_Gyroscope_Z_Std,time_Gyroscope_Z_Min,time_Gyroscope_Z_Max,time_Gyroscope_Z_Range,time_Gyroscope_Z_IQR,time_Gyroscope_Z_RMS,time_Gyroscope_Z_Energy,time_Acc_Magnitude_Mean,time_Acc_Magnitude_Median,time_Acc_Magnitude_Std,time_Acc_Magnitude_Min,time_Acc_Magnitude_Max,time_Acc_Magnitude_Range,time_Acc_Magnitude_IQR,time_Acc_Magnitude_RMS,time_Acc_Magnitude_Energy,time_Gyro_Magnitude_Mean,time_Gyro_Magnitude_Median,time_Gyro_Magnitude_Std,time_Gyro_Magnitude_Min,time_Gyro_Magnitude_Max,time_Gyro_Magnitude_Range,time_Gyro_Magnitude_IQR,time_Gyro_Magnitude_RMS,time_Gyro_Magnitude_Energy,freq_n_samples,freq_original_sampling_frequency_hz,freq_sampling_frequency_hz,freq_resampled_n_samples,freq_uniform_time_start_s,freq_uniform_time_end_s,freq_acc_x_dominant_frequency,freq_acc_x_spectral_centroid,freq_acc_x_spectral_entropy,freq_acc_x_spectral_power,freq_acc_y_dominant_frequency,freq_acc_y_spectral_centroid,freq_acc_y_spectral_entropy,freq_acc_y_spectral_power,freq_acc_z_dominant_frequency,freq_acc_z_spectral_centroid,freq_acc_z_spectral_entropy,freq_acc_z_spectral_power,freq_acc_magnitude_dominant_frequency,freq_acc_magnitude_spectral_centroid,freq_acc_magnitude_spectral_entropy,freq_acc_magnitude_spectral_power,freq_gyro_x_dominant_frequency,freq_gyro_x_spectral_centroid,freq_gyro_x_spectral_entropy,freq_gyro_x_spectral_power,freq_gyro_y_dominant_frequency,freq_gyro_y_spectral_centroid,freq_gyro_y_spectral_entropy,freq_gyro_y_spectral_power,freq_gyro_z_dominant_frequency,freq_gyro_z_spectral_centroid,freq_gyro_z_spectral_entropy,freq_gyro_z_spectral_power,freq_gyro_magnitude_dominant_frequency,freq_gyro_magnitude_spectral_centroid,freq_gyro_magnitude_spectral_entropy,freq_gyro_magnitude_spectral_power,symmetry_Accelerometer_X_Mean_difference,symmetry_Accelerometer_X_Median_difference,symmetry_Accelerometer_X_Std_difference,symmetry_Accelerometer_X_Min_difference,symmetry_Accelerometer_X_Max_difference,symmetry_Accelerometer_X_Range_difference,symmetry_Accelerometer_X_IQR_difference,symmetry_Accelerometer_X_RMS_difference,symmetry_Accelerometer_X_Energy_difference,symmetry_Accelerometer_Y_Mean_difference,symmetry_Accelerometer_Y_Median_difference,symmetry_Accelerometer_Y_Std_difference,symmetry_Accelerometer_Y_Min_difference,symmetry_Accelerometer_Y_Max_difference,symmetry_Accelerometer_Y_Range_difference,symmetry_Accelerometer_Y_IQR_difference,symmetry_Accelerometer_Y_RMS_difference,symmetry_Accelerometer_Y_Energy_difference,symmetry_Accelerometer_Z_Mean_difference,symmetry_Accelerometer_Z_Median_difference,symmetry_Accelerometer_Z_Std_difference,symmetry_Accelerometer_Z_Min_difference,symmetry_Accelerometer_Z_Max_difference,symmetry_Accelerometer_Z_Range_difference,symmetry_Accelerometer_Z_IQR_difference,symmetry_Accelerometer_Z_RMS_difference,symmetry_Accelerometer_Z_Energy_difference,symmetry_Gyroscope_X_Mean_difference,symmetry_Gyroscope_X_Median_difference,symmetry_Gyroscope_X_Std_difference,symmetry_Gyroscope_X_Min_difference,symmetry_Gyroscope_X_Max_difference,symmetry_Gyroscope_X_Range_difference,symmetry_Gyroscope_X_IQR_difference,symmetry_Gyroscope_X_RMS_difference,symmetry_Gyroscope_X_Energy_difference,symmetry_Gyroscope_Y_Mean_difference,symmetry_Gyroscope_Y_Median_difference,symmetry_Gyroscope_Y_Std_difference,symmetry_Gyroscope_Y_Min_difference,symmetry_Gyroscope_Y_Max_difference,symmetry_Gyroscope_Y_Range_difference,symmetry_Gyroscope_Y_IQR_difference,symmetry_Gyroscope_Y_RMS_difference,symmetry_Gyroscope_Y_Energy_difference,symmetry_Gyroscope_Z_Mean_difference,symmetry_Gyroscope_Z_Median_difference,symmetry_Gyroscope_Z_Std_difference,symmetry_Gyroscope_Z_Min_difference,symmetry_Gyroscope_Z_Max_difference,symmetry_Gyroscope_Z_Range_difference,symmetry_Gyroscope_Z_IQR_difference,symmetry_Gyroscope_Z_RMS_difference,symmetry_Gyroscope_Z_Energy_difference,symmetry_Acc_Magnitude_Mean_difference,symmetry_Acc_Magnitude_Median_difference,symmetry_Acc_Magnitude_Std_difference,symmetry_Acc_Magnitude_Min_difference,symmetry_Acc_Magnitude_Max_difference,symmetry_Acc_Magnitude_Range_difference,symmetry_Acc_Magnitude_IQR_difference,symmetry_Acc_Magnitude_RMS_difference,symmetry_Acc_Magnitude_Energy_difference,symmetry_Gyro_Magnitude_Mean_difference,symmetry_Gyro_Magnitude_Median_difference,symmetry_Gyro_Magnitude_Std_difference,symmetry_Gyro_Magnitude_Min_difference,symmetry_Gyro_Magnitude_Max_difference,symmetry_Gyro_Magnitude_Range_difference,symmetry_Gyro_Magnitude_IQR_difference,symmetry_Gyro_Magnitude_RMS_difference,symmetry_Gyro_Magnitude_Energy_difference
0,1,Healthy Control,0,56.0,NaN,173.0,78.0,Male,Right,Yes,Yes,Unknown,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000155,0.004059,0.074081,-0.513615,0.233092,0.746707,0.059540,0.074046,14.549401,0.000101,-0.000815,0.087478,-0.376868,0.441544,0.818412,0.066308,0.087440,15.694766,-0.000111,0.001951,0.092351,-0.514622,0.287520,0.802142,0.077791,0.092315,19.727217,0.001958,-0.007048,0.733113,-3.022237,2.744726,5.766962,0.454378,0.734694,1451.533057,-0.059348,-0.041810,0.680479,-1.848660,1.860104,3.708764,0.620630,0.689235,1062.160499,0.015561,0.018341,0.946153,-2.392659,2.397176,4.789835,0.904805,0.950492,2117.577259,0.104609,0.076229,0.101005,0.007341,0.872564,0.865224,0.082269,0.148856,49.971383,1.044496,0.770702,0.979678,0.016680,4.515957,4.499278,1.270267,1.454627,4631.270815,1255.272727,99.695771,100.0,1255.272727,0.0,12.542727,3.058122,6.230525,0.694262,0.012787,2.332340,5.676603,0.687384,0.013938,2.097765,5.248369,0.645296,0.020098,1.035917,5.406945,0.635161,0.025970,1.884724,3.646866,0.583616,1.226957,1.054769,2.351818,0.496097,0.982722,1.077794,2.210475,0.466672,1.788369,0.558197,2.891241,0.510830,1.563943,0.000126,0.000751,0.002687,0.020347,0.081354,0.061007,-0.001020,0.002685,3.926234,-0.000961,0.007324,0.000740,-0.250956,-0.224631,0.026325,0.007206,0.000733,0.501690,0.000144,-0.002419,-0.010846,0.119935,0.008180,-0.111756,-0.006738,-0.010827,-2.796376,-0.059027,0.001298,-0.183969,0.502048,-1.044879,-1.546927,0.030725,-0.186072,-763.401893,0.054845,0.026634,-0.056368,0.315671,-0.155424,-0.471095,-0.065901,-0.063544,-195.361523,-0.059173,-0.051094,-0.054036,0.280625,-0.138113,-0.418738,-0.137933,-0.053825,15.208446,-0.003837,-0.000955,-0.003630,-0.000847,-0.139103,-0.138256,-0.000969,-0.004155,1.631548,-0.126805,-0.085487,-0.123576,-0.007836,-0.317006,-0.309170,-0.028445,-0.179823,-943.554969
1,2,Other Movement Disorder,2,81.0,69.0,193.0,104.0,Male,Right,No,Unknown,No Effect,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,1,0,1,0,12,2,1,0,1,0,1,1,0,3,3,0.000043,-0.000302,0.062226,-0.365569,0.382510,0.748079,0.057380,0.062207,6.704495,-0.000565,-0.002381,0.104161,-0.519660,0.738762,1.258423,0.095721,0.104117,18.189232,-0.000027,0.002218,0.093746,-0.893036,0.324629,1.217665,0.072578,0.093704,17.435516,0.004577,0.005402,0.650489,-2.453989,2.730280,5.184269,0.561365,0.651251,969.586073,-0.005982,0.001440,0.489375,-1.470359,1.417012,2.887371,0.583114,0.496117,548.688799,-0.007127,-0.009160,0.432280,-1.367154,1.353047,2.720201,0.318673,0.436265,436.299754,0.114448,0.086625,0.109235,0.005603,1.169167,1.163564,0.086983,0.160501,42.329243,0.757657,0.606165,0.633197,0.024009,3.628187,3.604178,0.719134,1.001763,1954.574626,1255.272727,99.693186,100.0,1255.272727,0.0,12.542727,3.138301,5.626025,0.665201,0.004732,4.510022,6.712393,0.643320,0.020066,3.251639,6.144094,0.672994,0.012731,1.248212,5.421935,0.645448,0.018075,3.360618,4.732639,0.599669,1.017963,2.336848,3.158048,0.498420,0.455997,1.992735,2.448173,0.482142,0.353557,0.896013,3.300614,0.536026,0.704772,0.000311,0.003689,-0.000609,0.157281,-0.055430,-0.212710,0.003881,-0.000597,-0.070427,0.000056,0.004194,-0.034243,0.327178,-0.234006,-0.561184,-0.032424,-0.034220,-11.511198,0.000241,-0.002189,0.000195,0.247575,0.033844,-0.213731,0.012567,0.000196,-0.051752,-0.016074,0.017275,-0.131226,0.373396,-0.926270,-1.299666,-0.282290,-0.130117,-110.430912,0.068725,-0.047424,0.103311,-0.290733,0.284144,0.574877,0.084738,0.104329,280.149633,-0.034046,0.005500,-0.012717,0.131622,-0.025563,-0.157185,-0.075927,-0.012010,32.709000,-0.017563,-0.013608,-0.022999,0.001122,-0.291124,-0.292246,-0.028135,-0.029868,-11.633377,-0.064486,-0.106319,0.023457,-0.004497,-0.520227,-0.515729,-0.031305,-0.028431,202.427722
2,3,Healthy Control,0,45.0,NaN,170.0,78.0,Female,Right,No,Unknown,Unknown,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000092,-0.000014,0.089180,-0.364048,0.331769,0.695817,0.094730,0.089143,20.022262,-0.000301,-0.007162,0.094037,-0.318494,0.432975,0.751469,0.115303,0.094001,23.441925,0.000737,0.015611,0.135424,-0.688083,0.281203,0.969286,0.154435,0.135364,49.596858,0.029004,-0.011867,0.677988,-2.138622,2.153938,4.292560,0.649373,0.680796,1394.784319,0.021482,-0.007202,0.724062,-1.707368,1.946701,3.654068,0.919674,0.730784,1450.953032,-0.000909,0.005118,1.066673,-2.106831,2.132905,4.239737,1.579971,1.070579,4119.246211,0.156118,0.131845,0.102425,0.017890,0.807261,0.789371,0.088695,0.189295,93.061045,1.280202,1.214987,0.841563,0.051751,3.553962,3.502210,1.220953,1.565628,6964.983562,1255.272727,99.709030,100.0,1255.272727,0.0,12.542727,2.486811,5.291730,0.627177,0.020999,2.509985,5.976405,0.669272,0.022802,2.531371,4.691297,0.585639,0.049827,1.592921,4.871101,0.605607,0.024221,2.768852,3.821132,0.526641,1.590024,1.928390,2.822770,0.511789,1.428762,1.426565,2.503264,0.432065,4.204214,1.033793,3.088925,0.472244,1.678728,0.000396,-0.001194,0.005026,0.115035,0.146842,0.031807,0.007943,0.005028,2.695090,-0.001060,0.001880,0.007266,-0.136103,0.025483,0.161586,0.000323,0.007272,1.984549,0.000258,-0.005150,-0.003860,-0.066855,-0.014438,0.052417,-0.004143,-0.003866,-3.692288,0.026944,0.012724,0.095199,-0.862230,0.598981,1.461210,-0.000433,0.094778,466.946269,0.119367,0.047168,0.094969,-0.070942,0.548340,0.619282,-0.073892,0.099582,290.213950,-0.082715,-0.101567,0.033037,-0.317696,-0.242002,0.075694,0.041209,0.032811,168.383594,0.002917,0.002024,-0.001463,0.003127,-0.076150,-0.079277,-0.009884,0.001244,0.987351,0.068282,0.084292,0.060849,0.017704,0.438968,0.421265,0.056464,0.092100,925.543812
3,4,Parkinson's Disease,1,67.0,63.0,161.0,90.0,Female,Right,No,Unknown,No Effect,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,1,0,0,12,1,2,1,1,0,1,1,0,2,3,-0.000061,-0.000984,0.035592,-0.177022,0.220743,0.397765,0.024906,0.035588,4.321860,0.000041,-0.003340,0.047037,-0.181449,0.383989,0.565438,0.042677,0.047019,6.817805,0.000122,0.002667,0.057104,-0.433757,0.146561,0.580318,0.044076,0.057081,12.719649,0.033283,0.010237,0.381022,-1.100282,1.359733,2.460015,0.339980,0.385037,436.801061,-0.022131,-0.015391,0.367558,-0.909074,0.870891,1.779965,0.343455,0.378334,414.539711,0.010895,0.000858,0.494688,-1.054148,1.056314,2.110463,0.541144,0.504157,864.154799,0.056969,0.041472,0.059839,0.003204,0.640202,0.636999,0.037442,0.083185,23.859315,0.573044,0.487765,0.469875,0.008791,2.029775,2.020984,0.536433,0.756978,1715.495571,1255.272727,99.688082,100.0,1255.272727,0.0,12.542727,1.947578,6.481895,0.723869,0.004170,2.554732,6.340352,0.714052,0.006094,1.834426,6.317018,0.715528,0.012909,0.319821,4.691237,0.569417,0.012140,0.734762,2.900242,0.536754,0.455841,0.447727,1.512428,0.408111,0.405129,1.101155,1.652757,0.376839,0.878390,0.406483,1.821555,0.388259,0.476171,-0.000216,-0.003590,0.010988,0.067240,0.161462,0.094221,0.008039,0.010974,2.495382,0.000139,0.002171,-0.002178,0.015928,-0.285778,-0.301706,0.003137,-0.002181,-1.695210,0.000120,-0.000610,-0.001723,0.025174,-0.009372,-0.034546,-0.000607,-0.001721,-3.304850,0.008130,0.000249,0.003187,0.038054,0.032954,-0.005100,0.035377,0.006207,-111.997554,0.109129,0.003112,0.024357,0.151364,0.312854,0.161490,0.069241,0.018712,59.644272,-0.093433,-0.082899,-0.019947,-0.015903,-0.142037,-0.126134,0.056947,-0.022713,-17.439135,0.006131,0.005927,-0.003271,-0.001016,-0.178047,-0.177031,0.005030,0.001918,-2.504678,0.014927,0.036575,0.000743,0.001043,0.170965,0.169922,0.052439,0.012388,-69.792417
4,5,Parkinson's Disease,1,75.0,65.0,172.0,86.0,Male,Left,No,Unknown,Unknown,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,0,11,2,1,0,0,0,1,0,0,2,5,-0.000042,-0.000507,0.060632,-0.213993,0.233428,0.447422,0.075401,0.060610,6.021132,-0.000057,-0.004129,0.112425,-0.378152,0.487117,0.865269,0.134627,0.112379,21.995114,0.000093,0.000291,0.085675,-0.423143,0.275818,0.698960,0.101231,0.085640,13.777724,0.011549,-0.027006,0.645503,-1.912828,2.104835,4.017662,0.806418,0.646599,832.304926,0.004951,-0.006397,0.480587,-1.209166,1.141830,2.350996,0.679565,0.482465,479.121452,-0.001718,0.014468,0.625390,-1.488436,1.340937,2.829373,0.801986,0.630553,837.506745,0.132930,0.115005,0.082380,0.010615,0.643581,0.632966,0.087794,0.157051,41.793970,0.911229,0.839022,0.579518,0.032670,2.942777,2.910107,0.781414,1.093297,2148.933124,1255.272727,99.704327,100.0,1255.272727,0.0,12.542727,3.651080,5.317646,0.625702,0.004385,4.798063,6.003697,0.627012,0.016508,4.452608,5.510266,0.634168,0.011136,1.317027,6.100467,0.693698,0.008332,3.281073,4.893018,0.559370,0.635074,3.784277,3.503301,0.485392,0.459802,2.552124,2.723202,0.428897,0.744560,0.902012,3.742713,0.531731,0.418009,0.000666,0.004864,-0.028622,0.059647,-0.083144,-0.142791,-0.040769,-0.028618,-4.931818,0.000078,0.000180,-0.087726,0.280731,-0.307485,-0.588217,-0.113701,-0.087688,-27.370468,-0.000308,-0.002016,-0.036532,0.053178,-0.075571,-0.128750,-0.055824,-0.036522,-7.213784,0.020806,0.002986,-0.484805,1.458950,-0.909971,-2.368921,-0.713642,-0.482536,-918.820951,0.019364,-0.021701,-0.044140,0.151927,-0.150082,-0.302009,-0.107205,-0.043082,121.869381,-0.045455,-0.069661,-0.108596,0.250952,-0.380163,-0.631115,-0.179864,-0.104153,-36.109681,-0.087400,-0.079773,-0.042269,-0.009043,-0.245858,-0.236815,-0.061590,-0.096167,-39.516070,-0.404767,-0.398273,-0.190974,-0.010912,-1.140813,-1.129902,-0.373412,-0.428032,-833.061251

In [59]:
# =============================================================================
# Verify full multimodal feature structure
# =============================================================================

expected_full_features = (
    len(DEMOGRAPHIC_FEATURES)
    + len(QUESTIONNAIRE_FEATURES)
    + len(WEARABLE_FEATURES)
)

expected_full_columns = (3 + expected_full_features)

actual_full_features = (multimodal_full_df.shape[1] - 3)

print("Expected predictors:",
    expected_full_features
)

print("Actual predictors:",
    actual_full_features
)

print("Expected total columns:",
    expected_full_columns
)

print("Actual total columns:",
    multimodal_full_df.shape[1]
)

Expected predictors: 232
Actual predictors: 232
Expected total columns: 235
Actual total columns: 235

In [61]:
# =============================================================================
# Verify participant structure
# =============================================================================

assert len(multimodal_full_df) == 469, (
    "Full multimodal dataset does not contain "
    "469 participants."
)

assert multimodal_full_df[
    "patient_id"
].nunique() == 469, (
    "Unexpected missing or duplicated participant IDs."
)

duplicated_full_participants = (
    multimodal_full_df[
        "patient_id"
    ]
    .duplicated()
    .sum()
)

assert duplicated_full_participants == 0, (
    "Duplicated participants were introduced "
    "during multimodal integration."
)

assert multimodal_full_df.shape[1] == expected_full_columns, (
    f"Expected {expected_full_columns} total columns, "
    f"found {multimodal_full_df.shape[1]}."
)

print(
    "Full multimodal dataset verified"
)

Full multimodal dataset verified

In [63]:
# ======================================================================
# Integration summary
# ======================================================================

full_multimodal_summary = pd.DataFrame({
    "Metric": [
        "Patient_id",
        "Demographic features",
        "Questionnaire features",
        "Wearable features",
        "Total predictors",
        "Total columns",
        "Duplicated participants",
    ],
    "Value": [
        len(multimodal_full_df),
        len(DEMOGRAPHIC_FEATURES),
        len(QUESTIONNAIRE_FEATURES),
        len(WEARABLE_FEATURES),
        expected_full_features,
        multimodal_full_df.shape[1],
        duplicated_full_participants,
    ],
})

full_multimodal_summary

                    Metric  Value
0               Patient_id    469
1     Demographic features      9
2   Questionnaire features     41
3        Wearable features    182
4         Total predictors    232
5            Total columns    235
6  Duplicated participants      0

#### 8. Verify Class Distribution

In [64]:
# =============================================================================
# Define integrated datasets
# =============================================================================

integrated_datasets = {
    "Demographics + Questionnaire": demographics_questionnaire_df,
    "Wearable + Questionnaire": wearable_questionnaire_df,
    "Full Multimodal": multimodal_full_df,
}

In [65]:
# =============================================================================
# Calculate class distribution
# =============================================================================

class_distribution_rows = []

for dataset_name, dataframe in integrated_datasets.items():

    class_counts = (
        dataframe["condition_group"]
        .value_counts()
    )

    row = {
        "Dataset": dataset_name,
        "Patient_id": len(dataframe),
    }

    for class_name, count in class_counts.items():
        row[class_name] = count

    class_distribution_rows.append(row)


class_distribution_df = pd.DataFrame(
    class_distribution_rows
)

class_distribution_df

,Dataset,Patient_id,Parkinson's Disease,Other Movement Disorder,Healthy Control
0,Demographics + Questionnaire,469,276,114,79
1,Wearable + Questionnaire,469,276,114,79
2,Full Multimodal,469,276,114,79

#### Observation: 

The three integrated datasets retained the same 469 participants and identical diagnostic class distributions.

#### 9. Verify No Data Leakage

In [67]:
# =============================================================================
# Define non-predictor columns
# =============================================================================

NON_PREDICTOR_COLUMNS = [
    "patient_id",
    "condition_group",
    "label",
]

# =============================================================================
# Define expected predictor sets
# =============================================================================

expected_predictor_sets = {
    "Demographics + Questionnaire": (
        DEMOGRAPHIC_FEATURES
        + QUESTIONNAIRE_FEATURES
    ),

    "Wearable + Questionnaire": (
        WEARABLE_FEATURES
        + QUESTIONNAIRE_FEATURES
    ),

    "Full Multimodal": (
        DEMOGRAPHIC_FEATURES
        + QUESTIONNAIRE_FEATURES
        + WEARABLE_FEATURES
    ),
}

In [68]:
# =============================================================================
# Check for leakage columns in predictor sets
# =============================================================================

leakage_rows = []

for dataset_name, predictor_columns in expected_predictor_sets.items():

    leakage_columns = [
        column
        for column in NON_PREDICTOR_COLUMNS
        if column in predictor_columns
    ]

    leakage_rows.append({
        "Dataset": dataset_name,
        "Leakage Columns": (
            ", ".join(leakage_columns)
            if leakage_columns
            else "None"
        ),
        "Leakage Detected": (
            len(leakage_columns) > 0
        ),
    })


data_leakage_check = pd.DataFrame(
    leakage_rows
)

data_leakage_check

                        Dataset Leakage Columns  Leakage Detected
0  Demographics + Questionnaire            None             False
1      Wearable + Questionnaire            None             False
2               Full Multimodal            None             False

In [70]:
# =============================================================================
# Validate absence of leakage columns
# =============================================================================

assert not data_leakage_check[
    "Leakage Detected"
].any(), (
    "Potential target or identifier leakage was detected."
)

print(
    "No identifier or target Leakage detected "
    "in the predictor sets"
)

No identifier or target Leakage detected in the predictor sets

In [71]:
# =============================================================================
# Verify predictor columns against actual integrated datasets
# =============================================================================

integrated_predictor_validation = []

for dataset_name, dataframe in integrated_datasets.items():

    expected_predictors = set(
        expected_predictor_sets[dataset_name]
    )

    actual_predictors = set(
        dataframe.columns
    ) - set(NON_PREDICTOR_COLUMNS)

    same_predictors = (
        actual_predictors
        == expected_predictors
    )

    integrated_predictor_validation.append({
        "Dataset": dataset_name,
        "Expected Predictors": len(expected_predictors),
        "Actual Predictors": len(actual_predictors),
        "Predictor Set Match": same_predictors,
    })


predictor_validation_df = pd.DataFrame(
    integrated_predictor_validation
)

predictor_validation_df

,Dataset,Expected Predictors,Actual Predictors,Predictor Set Match
0,Demographics + Questionnaire,50,50,True
1,Wearable + Questionnaire,223,223,True
2,Full Multimodal,232,232,True

In [73]:
assert predictor_validation_df[
    "Predictor Set Match"
].all(), (
    "One or more integrated datasets contain "
    "unexpected predictor columns."
)

print(
    "Predictor sets verified "
    "with no unexpected Leakage columns"
)

Predictor sets verified with no unexpected Leakage columns

#### 10. Create Dataset Summary Table

This summary provides a final overview of the datasets prepared for the subsequent multimodal modeling experiments.

The table reports the number of patient_id, predictor features, and diagnostic class distribution for each integrated dataset.

In [74]:
# =============================================================================
# Create multimodal dataset summary
# =============================================================================

summary_rows = []

for dataset_name, dataframe in integrated_datasets.items():

    class_counts = (
        dataframe["condition_group"]
        .value_counts()
    )

    row = {
        "Dataset": dataset_name,
        "Patient_id": dataframe["patient_id"].nunique(),
        "Features": len(
            expected_predictor_sets[dataset_name]
        ),
    }

    # Add class distribution
    for class_name, count in class_counts.items():
        row[class_name] = count

    summary_rows.append(row)


dataset_summary = pd.DataFrame(
    summary_rows
)

dataset_summary

,Dataset,Patient_id,Features,Parkinson's Disease,Other Movement Disorder,Healthy Control
0,Demographics + Questionnaire,469,50,276,114,79
1,Wearable + Questionnaire,469,223,276,114,79
2,Full Multimodal,469,232,276,114,79

#### 11. Save and Verify Outputs

In [75]:
# =============================================================================
# Define multimodal dataset output paths
# =============================================================================

DEMOGRAPHICS_QUESTIONNAIRE_OUTPUT = (
    PROCESSED_DIR
    / "demographics_questionnaire.csv"
)

WEARABLE_QUESTIONNAIRE_OUTPUT = (
    PROCESSED_DIR
    / "wearable_questionnaire.csv"
)

MULTIMODAL_FULL_OUTPUT = (
    PROCESSED_DIR
    / "multimodal_full.csv"
)

In [76]:
# =============================================================================
# Save multimodal datasets
# =============================================================================

demographics_questionnaire_df.to_csv(
    DEMOGRAPHICS_QUESTIONNAIRE_OUTPUT,
    index=False,
)

wearable_questionnaire_df.to_csv(
    WEARABLE_QUESTIONNAIRE_OUTPUT,
    index=False,
)

multimodal_full_df.to_csv(
    MULTIMODAL_FULL_OUTPUT,
    index=False,
)

print("Multimodal datasets saved")

Multimodal datasets saved

In [79]:
# =============================================================================
# Save dataset summary table
# =============================================================================

outputs.save_table(
    dataset_summary,
    "multimodal_dataset_summary.csv",
)

print("Dataset summary table saved")

Dataset summary table saved

In [80]:
# =============================================================================
# Verify saved multimodal datasets
# =============================================================================

saved_dataset_files = {
    "Demographics + Questionnaire":
        DEMOGRAPHICS_QUESTIONNAIRE_OUTPUT,

    "Wearable + Questionnaire":
        WEARABLE_QUESTIONNAIRE_OUTPUT,

    "Full Multimodal":
        MULTIMODAL_FULL_OUTPUT,
}

for dataset_name, file_path in saved_dataset_files.items():

    assert file_path.exists(), (
        f"{dataset_name} output file was not saved."
    )

    assert file_path.stat().st_size > 0, (
        f"{dataset_name} output file is empty."
    )

print("All mutimodal dataset filed verified")

All mutimodal dataset filed verified

In [82]:
# =============================================================================
# Reload saved datasets
# =============================================================================

saved_demographics_questionnaire = pd.read_csv(
    DEMOGRAPHICS_QUESTIONNAIRE_OUTPUT,
    dtype={"patient_id": str},
)

saved_wearable_questionnaire = pd.read_csv(
    WEARABLE_QUESTIONNAIRE_OUTPUT,
    dtype={"patient_id": str},
)

saved_multimodal_full = pd.read_csv(
    MULTIMODAL_FULL_OUTPUT,
    dtype={"patient_id": str},
)

# =============================================================================
# Verify saved dataset dimensions
# =============================================================================

saved_dataset_validation = pd.DataFrame({
    "Dataset": [
        "Demographics + Questionnaire",
        "Wearable + Questionnaire",
        "Full Multimodal",
    ],
    "Participants": [
        saved_demographics_questionnaire[
            "patient_id"
        ].nunique(),

        saved_wearable_questionnaire[
            "patient_id"
        ].nunique(),

        saved_multimodal_full[
            "patient_id"
        ].nunique(),
    ],
    "Features": [
        saved_demographics_questionnaire.shape[1] - 3,
        saved_wearable_questionnaire.shape[1] - 3,
        saved_multimodal_full.shape[1] - 3,
    ],
    "Total Columns": [
        saved_demographics_questionnaire.shape[1],
        saved_wearable_questionnaire.shape[1],
        saved_multimodal_full.shape[1],
    ],
})

saved_dataset_validation

                        Dataset  Participants  Features  Total Columns
0  Demographics + Questionnaire           469        50             53
1      Wearable + Questionnaire           469       223            226
2               Full Multimodal           469       232            235

In [83]:
# =============================================================================
# Final output verification
# =============================================================================

assert (
    saved_dataset_validation["Participants"]
    == 469
).all(), (
    "Unexpected participant count after saving."
)

assert (
    saved_dataset_validation["Features"].tolist()
    == [50, 223, 232]
), (
    "Unexpected feature count after saving."
)

print("Final output verification passed")

Final output verification passed

#### Conclusion:

The multimodal data integration process was successfully completed at the participant level. Three datasets were created by combining the demographic, questionnaire, and wearable feature sets: 
- demographics_questionnaire.csv (50 predictors)
- wearable_questionnaire.csv (223 predictors)
- multimodal_full.csv (232 predictors)

All three integrated datasets retained the same 469 participants and preserved the diagnostic class distribution of the source data. Participant IDs were verified during integration, and no duplicated participants were introduced.